version: '3.3'

services:
  db:
    container_name: postgresMovieSite
    image: postgres:14.0
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  backend:
    container_name: backend-movieSite
    build:
      context: ./
    restart: unless-stopped
    environment:
      - PORT=${PORT}
# volumes:
#   pgdata:
