version: '3.3'

services:
  db:
    container_name: postgresMovieSite
    image: postgres:14.0
    restart: always
    environment:
      - POSTGRES_USER=edgar
      - POSTGRES_PASSWORD=20012002
      - POSTGRES_DB=movie-website
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    container_name: backend-movieSite
    build:
      context: ./
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  pgdata:
